### ISSUE TITLE
How could I use this action?

### ISSUE THREAD

**Issue by hubutui** [klakegg/actions-hugo#1]
Say, I wanna deploy my hugo blog to `username.github.io`, so I need to create a repo `username.github.io`, and create a `.github/workflows/hugo.yml` as documented in `README`? Or do I need to create another repo to host my hugo site, add `.github/workflows/hugo.yml`, and it automatically publish to `username.github.io`? Also, I don't see you mention GITHUB_TOKEN while some other actions use.

**Comment by klakegg** [comment]
This action may be used to perform the build step for a Hugo page. Publishing itself is out of scope.

Hosting using Github Pages is documented by Github.
