### ISSUE TITLE
config option `enableGitInfo` fails because of missing `git` binary

### ISSUE THREAD

**Issue by cengique** [klakegg/actions-hugo#8]
Can you include `git` in the Docker images, or is there a way we can get it installed before triggering `hugo`?

This is the option in the Hugo config that causes the error: https://gohugo.io/getting-started/configuration/#enablegitinfo 

Thanks.

**Comment by klakegg** [comment]
Did you use an [`ext` image](https://github.com/klakegg/docker-hugo#hugo-extended-edition)?

**Comment by cengique** [comment]
No, I wasn't. I was using `klakegg/actions-hugo@1.0.0`. Is the image updated? Did you want me to test?
